Added Zeromorph structs and DegreeCheck functionality for IpaPCS
EYBlockchain/jellyfish pull request #15
Opened 2023-11-30 14:00 UTC by Michael-EY

## Description

Introduced new struct ZeromorphHelper with methods (phi_poly, compute_qks, z_poly) that will ultimately be used in Zeromorph. Introduced new struct ZeromorphIsom with method that performs the Zeromorph isomorphism.

Rewritten the batch functionality for the IpaPCS. Introduced non-batch and batch version for performing DegreeCheck for the IpaPCS.

2023-11-30 15:27 UTC, Zyouell requested changes
Very nice! Only one thing to change and you weren't to know that this was an issue but all in all a very good job.

2023-11-30 15:27 UTC, Zyouell commented on plonk/src/nightfall/hops/univariate_ipa.rs
> +        let q_commitment_point = batch_proof.0 .0;
When we append the commitment to the transcript can we use the `append_curve_method()` because while what you have written works in practice when we want to verify things in a circuit if the curve we are working with doesn't have a Twisted Edwards form then we work with the point in Projective coordinates. The `append_curve_point()` method accounts for this.

2023-11-30 16:58 UTC, Michael-EY commented on plonk/src/nightfall/hops/univariate_ipa.rs
> +        let q_commitment_point = batch_proof.0 .0;
Updated to use `append_curve_point()`.

2023-12-01 08:35 UTC, Zyouell approved these changes

2023-12-01 08:36 UTC, merged