chore: Added Short Weierstrass compatibility
EYBlockchain/jellyfish pull request #7
Opened 2023-08-10 10:02 UTC by SwatiEY

2023-08-11 09:50 UTC, Zyouell requested changes
Overall it looks very good! Just a couple things to change. One larger one is that we will also have to make sure the `emulated_scalar_msm.rs` file works with all of the new changes. In addition unfortunately you have to run all of the tests yourself currently as I can't configure Github to perform those checks (I think Duncan has to do it).

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +        let x_eq = self.is_equal(point0.get_x(), point1.get_x())?;
We may have to use a `match` statement here as there is the possibility with SW points that the X and Y coordinate are the same but the Z one differs, plus we should handle the case where the points are of different types.

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +        match self{
Here `self` is a `PlonkCircuit<F>` so I don't know how this code will function. It would probably be best to change the function arguments to be something like `neutral_point_variable<P>(&self) -> PointVariable` and then add a `where` clause with `P: SWCurveConfig<BaseField = F>, F: SWToTEConParams`. Then because we have to implement `SWToTEConParams` for every field but they are all zero if the curve doesn't have a twisted Edward's form we could make it check if `S`,`NEG_ALPHA` and `BETA` are all zero, if they are then it will return the SW neutral point, if not it returns the TE neutral point.

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +                let b_y = self.is_equal(y, self.zero())?;
This line should be `let b_y = self.is_equal(y, self.one())?;`

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +                    let wire_vars = [x, x, y, y, 0];
We don't need to create the last variable here as it is never used.

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +
Nice!

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +                &TEPoint::from(p1.into_affine()),
I know I said before that we don't have to make `quaternary_point_select()` work, but I didn't realise that it was used in `fixed_base_scalar_mul()`. I apologise profusely but could we make both functions handle either SW or TE points?

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> +        // test_is_neutral_helper::<FqEd354, Param254>()?;
Could we write some tests that deal specifically with the SW case? As currently all of these tests rely on the curve having a twisted Edward's form. Also you can remove the tests for the `Bandersnatch` curve as there is currently no way to implement `SWToTEConParam` for both it and `JubJub` as they both have the same `BaseField`.

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/mod.rs
> -    pub fn variable_base_emulated_scalar_mul<P: Config<BaseField = F>>(
Is there a reason this function was removed?

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gadgets/ecc/msm.rs
> +            let res_point: TEPoint<F> = res.into_affine().into();
This is an example of where it would be good to have `From` implementations for both `SWAffine` and `TEAffine` for `PointWrapper<F>` as it would allow us to no have to worry about which type we are feeding in and simply write `let res_point: PointWrapper<F> = res.into_affine().into();`. The same goes in the next line which could be replaced with `let base_points: Vec<PointWrapper<F>> = bases.iter().map(|x| (*x).into()).collect();` and you wouldn't then have to convert to a `PointWrapper<F>` in a couple on lines time.

2023-08-11 09:50 UTC, Zyouell commented on relation/src/gates/ecc.rs
> +    -neg_a
An (admittingly pedantic so I apologise) change, could we either make both of these functions return the positive point or rename so that it is clear they are going to return the negative?

2023-09-19 16:06 UTC, Zyouell requested changes
So I changed the `plonk_ipa` branch to include a Github workflow so unfortunately you now need to rebase this on top of the most current version of `plonk_ipa` so that it will auto run all the required checks.

2023-10-17 16:09 UTC, Zyouell approved these changes

2023-10-18 09:03 UTC, jiajieey approved these changes

2023-10-18 09:03 UTC, merged

2023-10-18 09:05 UTC, Zyouell commented on plonk/src/nightfall/circuit/verify_ipa.rs
> +// }
I doidn't realise this was commented out I will fix that now.